export const NEXT_TURN = 'NEXT_TURN';
export const SET_INIT = 'SET_INIT';
export const GAME_START_TOGGLE = 'GAME_START_TOGGLE';
export const CHECKNUM_INIT = 'CHECKNUM_INIT';
export const CHECKNUM = 'CHECKNUM';
export const INIT_ONE_BINGO= 'INIT_ONE_BINGO';
export const INIT_TWO_BINGO= 'INIT_TWO_BINGO';
export const SET_ONE_BINGO = 'SET_ONE_BINGO';
export const SET_TWO_BINGO = 'SET_TWO_BINGO';